services:
  app:
    build:
      context: .
      target: production
    volumes: []
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    restart: always

  mongo:
    ports: []
    restart: always
